### ISSUE TITLE
[Request] How do I use this?

### ISSUE THREAD

**Issue by Artarian1** [MrDiamond64/EliteElixir#4]
This is a great project, incredible even, however; I have no clue on how to use this. Clearly it involves minecraft bedrock edition, that's great, now do I have it open or not, should I be at the menu or the realms page? Should I be in the server, do i have to manually enter the Microsoft account name or does it automatically target the owner? Lets take this back a little, what file do i even open??? A guide or a response would be great.

**Comment by Artarian1** [comment]
Sorry i accidentally closed it

**Comment by Artarian1** [comment]
OMG WHY

**Comment by EquineOsprey** [comment]
yeah man fr how to use this man

**Comment by thatkid662** [comment]
bruh i made an issue exactly like this but the owner closed it as done... dont see any guide tho...

**Comment by MrDiamond64** [comment]
> This is a great project, incredible even, however; I have no clue on how to use this. Clearly it involves minecraft bedrock edition, that's great, now do I have it open or not, should I be at the menu or the realms page? Should I be in the server, do i have to manually enter the Microsoft account name or does it automatically target the owner? Lets take this back a little, what file do i even open??? A guide or a response would be great.

Everything is automatic. You just need to open start.bat (or start.sh on Linux) and link your account.

From there, you will get a list of realms that aren't closed or expired. Beside the realm name there is a number, type that in and it will target that realm.

If you get a severIdConflict error then that means the account you linked is already inside the realm, leave the realm and try again.

**Comment by Artarian1** [comment]
I just tryed that, however it pulled up the command bar and said "node is not recognized as a internal or external command operable program or batch file".

**Comment by rosalgie** [comment]
> I just tryed that, however it pulled up the command bar and said "node is not recognized as a internal or external command operable program or batch file".

Who's gonna tell em?

**Comment by Artarian1** [comment]
As you can see from me accidentally closing the post each time i comment, i have never used github before, all i do is cheat on minecraft.

**Comment by Artarian1** [comment]
What, I bet someones about to say "The real force op is the friends we made along the way"

**Comment by Artarian1** [comment]
yeah yeah i got it node.js someone on discord told me.
