### ISSUE TITLE
It says you are now op But I don't have it and I restart it and it still does not give op

### ISSUE THREAD

**Issue by R3JASON42** [MrDiamond64/EliteElixir#7]
And how do give op to one user.

**Comment by MrDiamond64** [comment]
Mojang may have patched it on Realms, im currently investigating.

**Comment by R3JASON42** [comment]
And do you have a discord that I can join if you have an update?

**Comment by MrDiamond64** [comment]
> And do you have a discord that I can join if you have an update?

There is no discord at the moment.
